const calEvents = [
  {
    id: 0,
    activity: "Morning Trumpet Special",
    date: "2021-02-07",
    startTime: "06:00:00",
    endTime: "09:00:00",
    crew: [
      { id: 3, name: "Juma Ali", role: "Camera Operator" },
      { id: 45, name: "Ernesta John", role: "Camera Operator" },
      { id: 41, name: "Ravindah Kumar", role: "Sound Engineer" },
      { id: 12, name: "Abdul Mohammed", role: "Producer" },
      { id: 210, name: "Suleiman Mboma", role: "Switcher" },
      { id: 33, name: "Fatma Abdallah", role: "Presenter" },
    ],
    note: "Live studio event",
  },
  {
    id: 1,
    activity: "Adhuhuri Live",
    date: "2021-02-07",
    startTime: "13:00:00",
    endTime: "16:00:00",
    crew: [
      { id: 3, name: "Juma Ali", role: "Camera Operator" },
      { id: 45, name: "Ernesta John", role: "Camera Operator" },
      { id: 41, name: "Ravindah Kumar", role: "Sound Engineer" },
      { id: 12, name: "Abdul Mohammed", role: "Producer" },
      { id: 102, name: "Hekima Komba", role: "Switcher" },
      { id: 33, name: "Fatma Abdallah", role: "Presenter" },
    ],
    note: "Live studio event",
  },
  {
    id: 2,
    activity: "Alasiri Lounge",
    date: "2021-02-07",
    startTime: "16:00:00",
    endTime: "19:00:00",
    crew: [
      { id: 3, name: "Juma Ali", role: "Camera Operator" },
      { id: 45, name: "Ernesta John", role: "Camera Operator" },
      { id: 41, name: "Ravindah Kumar", role: "Sound Engineer" },
      { id: 12, name: "Abdul Mohammed", role: "Producer" },
      { id: 210, name: "Suleiman Mboma", role: "Switcher" },
      { id: 33, name: "Fatma Abdallah", role: "Presenter" },
    ],
    note: "Live studio event",
  },
  {
    id: 3,
    activity: "Habari",
    date: "2021-02-07",
    startTime: "20:00:00",
    endTime: "22:00:00",
    crew: [
      { id: 3, name: "Juma Ali", role: "Camera Operator" },
      { id: 45, name: "Ernesta John", role: "Camera Operator" },
      { id: 41, name: "Ravindah Kumar", role: "Sound Engineer" },
      { id: 12, name: "Abdul Mohammed", role: "Producer" },
      { id: 102, name: "Hekima Komba", role: "Switcher" },
      { id: 33, name: "Fatma Abdallah", role: "Presenter" },
    ],
    note: "Live studio event",
  },
];
