const calEvents = [
  {
    id: 0,
    activity: "Morning Trumpet Special",
    date: "2021-02-07",
    startTime: "06:00:00",
    endTime: "09:00:00",
    crew: [
      { id: 3, name: "Juma Ali", role: "Camera Operator" },
      { id: 45, name: "Ernesta John", role: "Camera Operator" },
      { id: 41, name: "Ravindah Kumar", role: "Sound Engineer" },
      { id: 12, name: "Abdul Mohammed", role: "Producer" },
      { id: 210, name: "Suleiman Mboma", role: "Switcher" },
      { id: 33, name: "Fatma Abdallah", role: "Presenter" },
    ],
    note: "Live studio event",
  },
  {
    id: 1,
    activity: "Adhuhuri Live",
    date: "2021-02-07",
    startTime: "13:00:00",
    endTime: "16:00:00",
    crew: [
      { id: 3, name: "Juma Ali", role: "Camera Operator" },
      { id: 45, name: "Ernesta John", role: "Camera Operator" },
      { id: 41, name: "Ravindah Kumar", role: "Sound Engineer" },
      { id: 12, name: "Abdul Mohammed", role: "Producer" },
      { id: 102, name: "Hekima Komba", role: "Switcher" },
      { id: 33, name: "Fatma Abdallah", role: "Presenter" },
    ],
    note: "Live studio event",
  },
  {
    id: 2,
    activity: "Alasiri Lounge",
    date: "2021-02-07",
    startTime: "16:00:00",
    endTime: "19:00:00",
    crew: [
      { id: 3, name: "Juma Ali", role: "Camera Operator" },
      { id: 45, name: "Ernesta John", role: "Camera Operator" },
      { id: 41, name: "Ravindah Kumar", role: "Sound Engineer" },
      { id: 12, name: "Abdul Mohammed", role: "Producer" },
      { id: 210, name: "Suleiman Mboma", role: "Switcher" },
      { id: 33, name: "Fatma Abdallah", role: "Presenter" },
    ],
    note: "Live studio event",
  },
  {
    id: 3,
    activity: "Habari",
    date: "2021-02-07",
    startTime: "20:00:00",
    endTime: "22:00:00",
    crew: [
      { id: 3, name: "Juma Ali", role: "Camera Operator" },
      { id: 45, name: "Ernesta John", role: "Camera Operator" },
      { id: 41, name: "Ravindah Kumar", role: "Sound Engineer" },
      { id: 12, name: "Abdul Mohammed", role: "Producer" },
      { id: 102, name: "Hekima Komba", role: "Switcher" },
      { id: 33, name: "Fatma Abdallah", role: "Presenter" },
    ],
    note: "Live studio event",
  },
];

//dummy activities
const activities = [
  {
    id: 0,
    status: "Open",
    name: "Simba vs Azam Live Match",
    nature: "Unscheduled",
    department: "Sports",
    region: "Dar es Salaam",
    venue: "Chamazi Stadium",
    date: "2021-02-12",
    startTime: "16:00:00",
    endTime: "18:00:00",
    resources: [
      {
        camera: ["CO1", "CO2", "CO3", "CO4", "CO5", "CO6"],
        sound: ["SE1", "SE2"],
        producer: ["PR1"],
        presenter: ["PS1", "PS2"],
        switcher: ["ST1", "ST2"],
        visual: ["VE1"],
        electrical: ["EE1"],
        lighting: ["LE1"],
        note: "Great Match",
      },
    ],
  },
  {
    id: 1,
    status: "Open",
    name: "Simba vs Azam Live Match",
    nature: "Unscheduled",
    department: "Sports",
    region: "Dar es Salaam",
    venue: "Chamazi Stadium",
    date: "2021-02-12",
    startTime: "16:00:00",
    endTime: "18:00:00",
    resources: [
      {
        camera: ["CO1", "CO2", "CO3", "CO4", "CO5", "CO6"],
        sound: ["SE1", "SE2"],
        producer: ["PR1"],
        presenter: ["PS1", "PS2"],
        switcher: ["ST1", "ST2"],
        visual: ["VE1"],
        electrical: ["EE1"],
        lighting: ["LE1"],
        note: "Great Match",
      },
    ],
  },
];
